### ISSUE TITLE
Bug: 404 Error link does not exist

### ISSUE THREAD

**Issue by DUFCLiam** [CoderDojoGitHub/beginners#4]
The link in "readme.md" does not exist.

**Comment by cameronmcefee** [comment]
Thanks for pointing that out @DUFCLiam.

@donjo, Looks like it's going to `coderdojosf.github.io/beginners` which is no longer active. I looked in https://github.com/CoderDojoGitHub/coderdojosf.github.io and https://github.com/CoderDojoGitHub/our-dojo but can't find any files or routes that indicate what was at `/beginners`. Any chance you remember what it pointed to?

**Comment by DUFCLiam** [comment]
I do not remember as I have only been park of the GitHub community for about one year sorry.

**Comment by DUFCLiam** [comment]
I clicked "Close and comment" by accident; Sorry.

**Comment by cameronmcefee** [comment]
Sorry for the confusion. I was actually asking @donjo, who originally added the link, if he remembers.

**Comment by DUFCLiam** [comment]
Oh, Thank you for notifying me!

**Comment by donjo** [comment]
Since we changed the organization name from CoderDojoSF to CoderDojoGithub the link is now http://coderdojogithub.github.io/beginners/ :+1:

**Comment by DUFCLiam** [comment]
Thanks for the quick response @donjo & @cameronmcefee

**Comment by cameronmcefee** [comment]
Fixed in dcb213103855599e3b44431c6a0503a02900055a

Thanks @donjo and @DUFCLiam!
